# GET https://2100-idx-marketplace-1718412182288.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/api/products
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiaWR4LW1hcmtldHBsYWNlLTE3MTg0MTIxODIyODguY2x1c3Rlci11eDVtbWxpYTN6aGhhc2s3cmlpaHJ1eHlkby5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3MTg0MTMxMTIsImV4cCI6MTcxODQxNjcxMX0.GYXqr9QjRgfHtWN6yPuMC-RBovgMwknavm74Rq5S0qvTvgId_Fg41IC1ekCVjIfeH3jzv37bN7RFn6ZJSAphT69gUfJF2cetMEd-Qm3QpMRxJD4NwXx9TQDLu6PZJ-f-WcoUD9KUOTlKDNlVot0PDi_f36doCsP8VnjMwudIXZjMqp5yjdVswBfMRvgG3Ao8iO5ncvqMA2hOdgKiPrsPcWmGVEHBdGqLM0qacGaov7GNa5W5MZNuInRL8KtbX_wfavzUtZ5Dkt8DZWc1rKZFSM9S8RZ2RfBL_Z-g_iNioXSFKxR3iQiJL7LTjgiKPNJb-TrLASX7qvFmqf2Y2LY3yA
# Content-Type: application/json

# POST https://2100-idx-marketplace-1718412182288.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/api/products
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiaWR4LW1hcmtldHBsYWNlLTE3MTg0MTIxODIyODguY2x1c3Rlci11eDVtbWxpYTN6aGhhc2s3cmlpaHJ1eHlkby5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3MTg0MTMxMTIsImV4cCI6MTcxODQxNjcxMX0.GYXqr9QjRgfHtWN6yPuMC-RBovgMwknavm74Rq5S0qvTvgId_Fg41IC1ekCVjIfeH3jzv37bN7RFn6ZJSAphT69gUfJF2cetMEd-Qm3QpMRxJD4NwXx9TQDLu6PZJ-f-WcoUD9KUOTlKDNlVot0PDi_f36doCsP8VnjMwudIXZjMqp5yjdVswBfMRvgG3Ao8iO5ncvqMA2hOdgKiPrsPcWmGVEHBdGqLM0qacGaov7GNa5W5MZNuInRL8KtbX_wfavzUtZ5Dkt8DZWc1rKZFSM9S8RZ2RfBL_Z-g_iNioXSFKxR3iQiJL7LTjgiKPNJb-TrLASX7qvFmqf2Y2LY3yA
# Content-Type: application/json

# {
#     "name": "spoon",
#     "description": "This is a spoon",
#     "price": 3.99,
#     "quantity": 1,
#     "category": "Housewares"
# }

# DELETE https://2100-idx-marketplace-1718412182288.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/api/products
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiaWR4LW1hcmtldHBsYWNlLTE3MTg0MTIxODIyODguY2x1c3Rlci11eDVtbWxpYTN6aGhhc2s3cmlpaHJ1eHlkby5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3MTg0MTMxMTIsImV4cCI6MTcxODQxNjcxMX0.GYXqr9QjRgfHtWN6yPuMC-RBovgMwknavm74Rq5S0qvTvgId_Fg41IC1ekCVjIfeH3jzv37bN7RFn6ZJSAphT69gUfJF2cetMEd-Qm3QpMRxJD4NwXx9TQDLu6PZJ-f-WcoUD9KUOTlKDNlVot0PDi_f36doCsP8VnjMwudIXZjMqp5yjdVswBfMRvgG3Ao8iO5ncvqMA2hOdgKiPrsPcWmGVEHBdGqLM0qacGaov7GNa5W5MZNuInRL8KtbX_wfavzUtZ5Dkt8DZWc1rKZFSM9S8RZ2RfBL_Z-g_iNioXSFKxR3iQiJL7LTjgiKPNJb-TrLASX7qvFmqf2Y2LY3yA
# Content-Type: application/json

# GET https://2100-idx-marketplace-1718412182288.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/api/products/666cf5821f5024fe47665782
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiaWR4LW1hcmtldHBsYWNlLTE3MTg0MTIxODIyODguY2x1c3Rlci11eDVtbWxpYTN6aGhhc2s3cmlpaHJ1eHlkby5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3MTg0MTMxMTIsImV4cCI6MTcxODQxNjcxMX0.GYXqr9QjRgfHtWN6yPuMC-RBovgMwknavm74Rq5S0qvTvgId_Fg41IC1ekCVjIfeH3jzv37bN7RFn6ZJSAphT69gUfJF2cetMEd-Qm3QpMRxJD4NwXx9TQDLu6PZJ-f-WcoUD9KUOTlKDNlVot0PDi_f36doCsP8VnjMwudIXZjMqp5yjdVswBfMRvgG3Ao8iO5ncvqMA2hOdgKiPrsPcWmGVEHBdGqLM0qacGaov7GNa5W5MZNuInRL8KtbX_wfavzUtZ5Dkt8DZWc1rKZFSM9S8RZ2RfBL_Z-g_iNioXSFKxR3iQiJL7LTjgiKPNJb-TrLASX7qvFmqf2Y2LY3yA
# Content-Type: application/json

# PUT https://2100-idx-marketplace-1718412182288.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/api/products/666cf5821f5024fe47665782
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiaWR4LW1hcmtldHBsYWNlLTE3MTg0MTIxODIyODguY2x1c3Rlci11eDVtbWxpYTN6aGhhc2s3cmlpaHJ1eHlkby5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3MTg0MTMxMTIsImV4cCI6MTcxODQxNjcxMX0.GYXqr9QjRgfHtWN6yPuMC-RBovgMwknavm74Rq5S0qvTvgId_Fg41IC1ekCVjIfeH3jzv37bN7RFn6ZJSAphT69gUfJF2cetMEd-Qm3QpMRxJD4NwXx9TQDLu6PZJ-f-WcoUD9KUOTlKDNlVot0PDi_f36doCsP8VnjMwudIXZjMqp5yjdVswBfMRvgG3Ao8iO5ncvqMA2hOdgKiPrsPcWmGVEHBdGqLM0qacGaov7GNa5W5MZNuInRL8KtbX_wfavzUtZ5Dkt8DZWc1rKZFSM9S8RZ2RfBL_Z-g_iNioXSFKxR3iQiJL7LTjgiKPNJb-TrLASX7qvFmqf2Y2LY3yA
# Content-Type: application/json

# {
#     "name": "bowl",
#     "description": "This is a bowl",
#     "price": 4.99,
#     "quantity": 2,
#     "category": "Housewares"
# }

DELETE https://2100-idx-marketplace-1718412182288.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/api/products/666cf5821f5024fe47665782
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vd29ya3N0YXRpb25zIiwiYXVkIjoiaWR4LW1hcmtldHBsYWNlLTE3MTg0MTIxODIyODguY2x1c3Rlci11eDVtbWxpYTN6aGhhc2s3cmlpaHJ1eHlkby5jbG91ZHdvcmtzdGF0aW9ucy5kZXYiLCJpYXQiOjE3MTg0MTMxMTIsImV4cCI6MTcxODQxNjcxMX0.GYXqr9QjRgfHtWN6yPuMC-RBovgMwknavm74Rq5S0qvTvgId_Fg41IC1ekCVjIfeH3jzv37bN7RFn6ZJSAphT69gUfJF2cetMEd-Qm3QpMRxJD4NwXx9TQDLu6PZJ-f-WcoUD9KUOTlKDNlVot0PDi_f36doCsP8VnjMwudIXZjMqp5yjdVswBfMRvgG3Ao8iO5ncvqMA2hOdgKiPrsPcWmGVEHBdGqLM0qacGaov7GNa5W5MZNuInRL8KtbX_wfavzUtZ5Dkt8DZWc1rKZFSM9S8RZ2RfBL_Z-g_iNioXSFKxR3iQiJL7LTjgiKPNJb-TrLASX7qvFmqf2Y2LY3yA
Content-Type: application/json